# Repo Info
owner: lissy93
repo: uptime
user-agent: lissy93

# Sites to monitor
sites:
  - name: Awesome Privacy
    url: https://awesome-privacy.xyz
  - name: Go-APOD
    url: https://apod.as93.net/
  - name: Email Comparison
    url: https://email-comparison.as93.net
  - name: Dashy Docs
    url: https://dashy.to
  - name: Countries
    url: https://countries.as93.net
  - name: Cyber Presentation
    url: https://cyber-presentation.as93.net
  - name: AliciaSykes.com
    url: https://aliciasykes.com
  - name: Sentiment Sweep
    url: https://sentiment-sweep.com
  - name: Security List
    url: https://security-list.js.org
  - name: Demo - Dashy
    url: https://dashy-demo-2.as93.net
  - name: Demo- Happy App
    url: http://happy-app-demo.as93.net
  - name: Demo - Lift Dash
    url: https://tfl-lift-dash.as93.net
  - name: Revision Quizzes
    url: https://revisionquizzes.com
  - name: Email Extractor
    url: https://email-extractor.as93.net
  - name: AHK to Espanso
    url: http://ahk-to-espanso.as93.net
  - name: Bullet Convertor
    url: http://bullet-convertor.as93.net
  - name: Tic-Tac-Toe
    url: http://tic-tac-toe.as93.net
  - name: Reference - TCP ping
    url: 1.1.1.1

# Website Data
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: uptime.as93.net
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://i.ibb.co/fkpSwVg/liss-bot-round.png
  name: Uptime Monitor
  introTitle: |
    Uptime monitoring of [@Lissy93](https://github.com/lissy93)'s repository docs and demo sites
  introMessage: |
    The following page shows current and recent uptime and outage statistics for application demos and docs sites.
    It's built using [upptime](https://github.com/upptime/upptime) and all checks are run via GitHub Actions.
  theme: ocean
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
# CI Running Options
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/30 * * * *"
  
# See https://upptime.js.org/docs/configuration
