# Repo Info
owner: lissy93
repo: uptime

# Sites to monitor
sites:
  - name: Personal Website
    url: https://aliciasykes.com
  - name: Sentiment Sweep
    url: https://sentiment-sweep.com
  - name: Security List
    url: https://security-list.js.org
  - name: Demo - Dashy
    url: https://dashy-demo-2.as93.net
  - name: Demo- Happy App
    url: http://happy-app-demo.as93.net
  - name: Demo - Lift Dash
    url: https://tfl-lift-dash.as93.net
  - name: Revision Quizzes
    url: https://revisionquizzes.com
  - name: Reference - TCP ping
    url: 1.1.1.1

# Website Data
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: uptime.as93.net
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://i.ibb.co/n3cR0vC/favicon.png
  name: Upptime
  introTitle: "Status Page for monitoring my GitHub application demo sites"
  introMessage: Status page showing real-time stats with GitHub actions using [upptime](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# See https://upptime.js.org/docs/configuration
